### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by mail2dijaw** [writetomdw/github-crash-course#1]
Blue title looks nice. It can be changed like this

```css

h1 {
  color: #2e029b;
}

```
